version: '3.8'
services:
  svm_service:
    image: svm_service
    container_name: svm_service
    command: tail -f /dev/null
    ports:
      - "5001:5001"
    networks:
      - app_network  

  vgg_service:
    image: vgg_service
    container_name: vgg_service
    command: tail -f /dev/null
    ports:
      - "5002:5002"
    networks:
      - app_network  

  frontend:
    image: frontend
    container_name: frontend
    command: tail -f /dev/null
    ports:
      - "5000:5000"
    depends_on:
      - svm_service
      - vgg_service
    networks:
      - app_network  
networks:
  app_network:
    driver: bridge